repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: mixed-line-ending
        args: ['--fix=auto']

-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: 'v3.0.0'
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [refactor, chore, build, ci, docs, feat, fix, test, perf, style, ":boom:"]

-   repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.7
    hooks:
    -   id: ripsecrets

-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.63.1
    hooks:
    -   id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["commit"]

-   repo: local
    hooks:
    - id: check envrc encryption
      name: check envrc encryption
      entry: ./scripts/check_envrc_encryption.sh
      language: script
      files: .envrc
